# Generated by Django 5.2.8 on 2025-12-09 16:14

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Peluquería')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empresa (Peluquería)',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci_ruc', models.CharField(max_length=20, verbose_name='C.I. o RUC')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='core.empresa')),
            ],
            options={
                'ordering': ['nombre', 'apellido'],
                'unique_together': {('empresa', 'ci_ruc')},
            },
        ),
        migrations.CreateModel(
            name='CategoriaGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_gasto', to='core.empresa')),
            ],
            options={
                'ordering': ['nombre'],
                'unique_together': {('empresa', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=0, max_digits=10)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.categoriagasto')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='core.empresa')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='profesionales/')),
                ('porcentaje_comision', models.IntegerField(default=50, verbose_name='Porcentaje de Comisión (%)')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesionales', to='core.empresa')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre', 'apellido'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_estimado', models.DecimalField(decimal_places=0, max_digits=10)),
                ('duracion_minutos', models.PositiveIntegerField(default=30)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='core.empresa')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('monto_cobrado', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('REALIZADO', 'Realizado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia / QR'), ('TARJETA', 'Tarjeta de Débito/Crédito'), ('CHEQUE', 'Cheque'), ('OTRO', 'Otro')], default='EFECTIVO', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='core.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='core.empresa')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='core.profesional')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('abierto', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='core.empresa')),
            ],
            options={
                'ordering': ['dia_semana'],
                'unique_together': {('empresa', 'dia_semana')},
            },
        ),
    ]
