# Generated by Django 5.2.8 on 2026-01-15 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='notas_adicionales',
            field=models.TextField(blank=True, null=True, verbose_name='Detalles / Adicionales'),
        ),
    ]
