# Generated by Django 5.2.8 on 2025-12-01 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cita'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombre', 'apellido']},
        ),
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['nombre']},
        ),
        migrations.AddField(
            model_name='profesional',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='profesionales/'),
        ),
    ]
