# Generated by Django 5.2.8 on 2025-12-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cliente_options_alter_servicio_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='monto_cobrado',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
