# Generated by Django 5.2.8 on 2025-12-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_categoriagasto_gasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='porcentaje_comision',
            field=models.IntegerField(default=50, verbose_name='Porcentaje de Comisión (%)'),
        ),
    ]
