# Generated by Django 5.2.8 on 2025-12-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_profesional_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia / QR'), ('TARJETA', 'Tarjeta de Débito/Crédito'), ('CHEQUE', 'Cheque'), ('OTRO', 'Otro')], default='EFECTIVO', max_length=20),
        ),
    ]
